Create lessons for users
framgia/ph_sels_rails_johnedel pull request #15
Opened 2019-07-26 10:10 UTC by johnedelmapa

PR description: Create lessons for users
Content: Users can start a lesson
[Commands]
rails db:migrate:reset db:seed
rails db:server 

[Pre-conditions]
To test the module user need to login
go to categories and choose one lesson
users can answer lessons

to check more go to the database
there should be data in the lessons table and answers table associated to each other

[Expected Output]
Users can answer lessons created by the admin users. 
			
[Notes]
There is still no error traps where users can not answer, answered lessons
and there is still no result table.

2019-07-27 12:31 UTC, inahsanjuan requested changes

2019-07-27 12:31 UTC, inahsanjuan commented on app/controllers/answers_controller.rb
> +    @answer.save
@johnedelmapa
You can shorten these 2 lines by just using the `create` method
`@answer = @lesson.answers.create(answer_params)`

2019-07-27 12:31 UTC, inahsanjuan commented on db/migrate/20190724125411_create_lessons.rb
> +      t.integer :score, default: false
@johnedelmapa 
Why is this `false`, while type is **integer** ?
Please update

2019-07-29 02:42 UTC, ivanraybuglosa commented
Please display the current word progress of the user. Like (1 of 3), (2 of 3), (3 of 3)...

2019-07-29 06:00 UTC, merged